"""Add fish_stress_records table for per-fish stress detection

Revision ID: 7578342d3035
Revises: b24f9b939db2
Create Date: 2026-07-23 19:26:37.219230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7578342d3035'
down_revision: Union[str, None] = 'b24f9b939db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
