"""Add fish_stress_records table

Revision ID: 9655dfe87ab3
Revises: 7578342d3035
Create Date: 2026-07-26 18:31:56.618535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9655dfe87ab3'
down_revision: Union[str, None] = '7578342d3035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
