"""Initial tables: Tank, SensorReading, BehaviorReading, StressScore, Alert

Revision ID: b24f9b939db2
Revises: 
Create Date: 2026-06-17 12:26:04.790514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24f9b939db2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('fish_species', sa.String(length=100), nullable=True),
    sa.Column('fish_count', sa.Integer(), nullable=True),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanks_id'), 'tanks', ['id'], unique=False)
    op.create_index(op.f('ix_tanks_tank_id'), 'tanks', ['tank_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='stresslevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('buzzer_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_tank_status', 'alerts', ['tank_id', 'status'], unique=False)
    op.create_table('behavior_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('fish_count', sa.Integer(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_acceleration', sa.Float(), nullable=True),
    sa.Column('turning_frequency', sa.Float(), nullable=True),
    sa.Column('motion_variability', sa.Float(), nullable=True),
    sa.Column('surface_visits', sa.Integer(), nullable=True),
    sa.Column('bottom_dwelling', sa.Float(), nullable=True),
    sa.Column('inactivity_pct', sa.Float(), nullable=True),
    sa.Column('schooling_density', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_readings_id'), 'behavior_readings', ['id'], unique=False)
    op.create_index('ix_behavior_readings_tank_timestamp', 'behavior_readings', ['tank_id', 'timestamp'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('dissolved_o2', sa.Float(), nullable=True),
    sa.Column('ammonia', sa.Float(), nullable=True),
    sa.Column('turbidity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index('ix_sensor_readings_tank_timestamp', 'sensor_readings', ['tank_id', 'timestamp'], unique=False)
    op.create_table('stress_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('fsi_score', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='stresslevel'), nullable=False),
    sa.Column('water_quality_score', sa.Float(), nullable=True),
    sa.Column('behavioral_score', sa.Float(), nullable=True),
    sa.Column('sensor_reading_id', sa.Integer(), nullable=True),
    sa.Column('behavior_reading_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['behavior_reading_id'], ['behavior_readings.id'], ),
    sa.ForeignKeyConstraint(['sensor_reading_id'], ['sensor_readings.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_scores_computed_at'), 'stress_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_stress_scores_id'), 'stress_scores', ['id'], unique=False)
    op.create_index('ix_stress_scores_tank_computed', 'stress_scores', ['tank_id', 'computed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stress_scores_tank_computed', table_name='stress_scores')
    op.drop_index(op.f('ix_stress_scores_id'), table_name='stress_scores')
    op.drop_index(op.f('ix_stress_scores_computed_at'), table_name='stress_scores')
    op.drop_table('stress_scores')
    op.drop_index('ix_sensor_readings_tank_timestamp', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('ix_behavior_readings_tank_timestamp', table_name='behavior_readings')
    op.drop_index(op.f('ix_behavior_readings_id'), table_name='behavior_readings')
    op.drop_table('behavior_readings')
    op.drop_index('ix_alerts_tank_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('ix_alerts_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_tanks_tank_id'), table_name='tanks')
    op.drop_index(op.f('ix_tanks_id'), table_name='tanks')
    op.drop_table('tanks')
    # ### end Alembic commands ###
